use chrono::{DateTime, NaiveDate, Utc};
use rust_decimal::Decimal;
use serde::Serialize;
use sqlx::FromRow;

#[derive(Debug, Serialize, FromRow)]
pub struct VehicleCacheRow {
    pub id: i32,
    pub car_no_plate: String,
    pub car_type: Option<String>,
    pub transporter: Option<String>,
    pub tank_capacity: Option<i32>,
    pub json_compartments: Option<serde_json::Value>,
    pub license_expiration_date: Option<NaiveDate>,
    pub calibration_expiration_date: Option<NaiveDate>,
    pub tank_license_expiration_date: Option<NaiveDate>,
    pub is_in_trip: bool,
    pub is_approved: bool,
    pub location: Option<String>,
    pub lat: Option<Decimal>,
    pub long: Option<Decimal>,
    pub location_time_stamp: Option<DateTime<Utc>>,
    pub engine_status: Option<String>,
    pub speed: Option<i32>,
    pub last_fuel_odometer: Option<i32>,
    pub last_oil_change_id: Option<i32>,
    pub driver_id: Option<i32>,
    pub operating_company: Option<String>,
    pub operating_area: Option<String>,
    pub geo_fence: Option<String>,
    pub slack_status: Option<String>,
    pub last_updated_slack_status: Option<DateTime<Utc>>,
    pub etit_car_id: Option<String>,
    pub car_license_url: Option<String>,
    pub car_license_back_url: Option<String>,
    pub calibration_license_url: Option<String>,
    pub calibration_license_back_url: Option<String>,
    pub tank_license_url: Option<String>,
    pub tank_license_back_url: Option<String>,
    pub raw_payload: serde_json::Value,
    pub source_created_at: Option<DateTime<Utc>>,
    pub source_updated_at: Option<DateTime<Utc>>,
    pub source_deleted_at: Option<DateTime<Utc>>,
    pub fetched_at: DateTime<Utc>,
}
